FROM node:20-alpine

WORKDIR /app

# Copy package files for dependency installation
COPY package.json package-lock.json* ./
RUN npm install

# We will mount the rest of the code via docker-compose
CMD ["npm", "run", "dev"]