version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: optician_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: optician_backend
    restart: always
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app  # Mount source for hot-reloading
    depends_on:
      - db
    networks:
      - ecommerce_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: optician_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent local node_modules from overwriting container's
    depends_on:
      - backend
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge