FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y gcc libpq-dev && apt-get clean
COPY requirements.txt .
# نصب Gunicorn در کنار نیازمندی‌ها
RUN pip install --no-cache-dir -r requirements.txt gunicorn 
COPY . .

# استفاده از Gunicorn با ورکرهای Uvicorn برای تحمل ترافیک بالا
CMD ["gunicorn", "app.main:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000"]