"""add prescription to order items

Revision ID: 13003fb4b02d
Revises: e40614da04e8
Create Date: 2026-07-07 15:12:10.123381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13003fb4b02d'
down_revision: Union[str, None] = 'e40614da04e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('prescription', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'prescription')
    # ### end Alembic commands ###
