"""add missing fields to product

Revision ID: 81191231e0aa
Revises: 81fbe1486255
Create Date: 2026-07-11 21:31:52.322512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81191231e0aa'
down_revision: Union[str, None] = '81fbe1486255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(), server_default='GLASSES', nullable=False))    
    op.add_column('products', sa.Column('is_prescription_ready', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('specifications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'is_prescription_ready')
    op.drop_column('products', 'product_type')
    op.drop_column('product_images', 'sort_order')
    # ### end Alembic commands ###
