"""add_indexes_for_performance_fixed

Revision ID: 81fbe1486255
Revises: 576c442e7f15
Create Date: 2026-07-09 16:51:34.453745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81fbe1486255'
down_revision: Union[str, None] = '576c442e7f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('addresses', sa.Column('province', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_addresses_is_default'), 'addresses', ['is_default'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.drop_column('addresses', 'phone_number')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.add_column('home_sections', sa.Column('config', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_home_sections_is_active'), 'home_sections', ['is_active'], unique=False)
    op.create_index(op.f('ix_home_sections_order'), 'home_sections', ['order'], unique=False)
    op.add_column('order_items', sa.Column('total_price', sa.Float(), nullable=False))
    op.alter_column('order_items', 'variant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_variant_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'PROCESSING', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'),
               nullable=False)
    op.create_index(op.f('ix_orders_is_paid'), 'orders', ['is_paid'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'receipt_number')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'payment_date')
    op.drop_column('orders', 'shipping_company')
    op.drop_column('orders', 'transaction_id')
    op.drop_column('orders', 'shipping_cost')
    op.create_index(op.f('ix_product_images_variant_id'), 'product_images', ['variant_id'], unique=False)
    op.drop_column('product_images', 'sort_order')
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'brand_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_products_product_type', table_name='products')
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'is_prescription_ready')
    op.drop_column('products', 'specifications')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.add_column('products', sa.Column('specifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_prescription_ready', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.create_index('ix_products_product_type', 'products', ['product_type'], unique=False)
    op.alter_column('products', 'brand_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.add_column('product_images', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_product_images_variant_id'), table_name='product_images')
    op.add_column('orders', sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('receipt_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_paid'), table_name='orders')
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'PROCESSING', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'),
               nullable=True)
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'is_paid')
    op.drop_column('orders', 'discount_amount')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_variant_id_fkey', 'order_items', 'product_variants', ['variant_id'], ['id'])
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.alter_column('order_items', 'variant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('order_items', 'total_price')
    op.drop_index(op.f('ix_home_sections_order'), table_name='home_sections')
    op.drop_index(op.f('ix_home_sections_is_active'), table_name='home_sections')
    op.drop_column('home_sections', 'config')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.add_column('addresses', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_is_default'), table_name='addresses')
    op.drop_column('addresses', 'province')
    op.drop_column('addresses', 'city')
    # ### end Alembic commands ###
